"""
generator.py — Prompt extraction, file saving, and iteration I/O.
"""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path
from typing import Optional

from . import display as ui

NUM_AGENTS = 7


# ═════════════════════════════════════════════════════════════════════════════
# PROMPT EXTRACTION
# ═════════════════════════════════════════════════════════════════════════════

def extract_agent_prompts(plan_text: str) -> list[str]:
    """
    Parse the plan text and extract the 7 individual agent prompts.

    Handles two common patterns the LLM produces:
        **AGENT N - Role**   (markdown bold)
        ## AGENT N - Role    (markdown heading)

    Returns a list of up to 7 prompt strings, each including the header line.
    """
    prompts:      list[str] = []
    current:      list[str] = []
    in_prompt:    bool      = False

    # Compile pattern once
    agent_header = re.compile(r"^(\*\*AGENT\s+\d+|##\s*AGENT\s+\d+)", re.IGNORECASE)

    for line in plan_text.splitlines():
        if agent_header.match(line.strip()):
            # Flush previous
            if current:
                prompts.append("\n".join(current).strip())
            current   = [line]
            in_prompt = True
            continue

        if in_prompt:
            # Stop at the INSTRUCTIONS section
            if line.strip().startswith("=== INSTRUCTIONS"):
                if current:
                    prompts.append("\n".join(current).strip())
                in_prompt = False
                break
            current.append(line)

    # Catch last prompt if file ends without INSTRUCTIONS section
    if in_prompt and current:
        prompts.append("\n".join(current).strip())

    return prompts[:NUM_AGENTS]


# ═════════════════════════════════════════════════════════════════════════════
# FILE SAVING
# ═════════════════════════════════════════════════════════════════════════════

def save_plan(plan_text: str, output_dir: str = ".") -> str:
    """
    Save the full plan to a timestamped Markdown file.

    Parameters
    ----------
    plan_text  : full plan string
    output_dir : directory to write into (default: cwd)

    Returns
    -------
    Absolute path of the saved file as a string.
    """
    ts       = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = Path(output_dir).resolve() / f"supervisor_plan_{ts}.md"

    header = (
        f"# Supervisor Plan — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
        f"Generated by [swarm-supervisor](https://github.com/plexhedge/swarm-supervisor)\n\n"
        "---\n\n"
    )
    out_path.write_text(header + plan_text, encoding="utf-8")
    return str(out_path)


# ═════════════════════════════════════════════════════════════════════════════
# ITERATION INPUT COLLECTION
# ═════════════════════════════════════════════════════════════════════════════

def collect_agent_results() -> str:
    """
    Prompt the user to paste all 7 agent outputs into the terminal.
    Returns the combined pasted text.
    """
    ui.blank()
    ui.display_iteration_instructions()
    ui.blank()

    lines: list[str] = []
    while True:
        try:
            line = input()
        except EOFError:
            break
        if line.strip().upper() == "END":
            break
        lines.append(line)

    return "\n".join(lines)
